version: "3"

services:
  frontend:
    image: docker-hub.montreal.aniere.fr/coiffex/frontend:latest
    restart: always
    ports:
      - 127.0.0.1:9080:80
    labels:
      - com.centurylinklabs.watchtower.enable=true

  backend:
    image: docker-hub.montreal.aniere.fr/coiffex/backend:latest
    restart: always
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres-db:5432/coiffex
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=mdp
    ports:
      - 127.0.0.1:9081:8080
    labels:
      - com.centurylinklabs.watchtower.enable=true
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:latest
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mdp
      POSTGRES_DB: coiffex   
