version: "3"

services:
  frontend:
    image: docker-hub.montreal.aniere.fr/coiffex/frontend:latest
    restart: always
    ports:
      - 127.0.0.1:9080:80
    labels:
      - com.centurylinklabs.watchtower.enable=true

  backend:
    image: docker-hub.montreal.aniere.fr/coiffex/backend:latest
    restart: always
    ports:
      - 127.0.0.1:9081:8080
    labels:
      - com.centurylinklabs.watchtower.enable=true
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: coiffex2023!
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - ./mongo-db-data:/data/db
      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 127.0.0.1:8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: coiffex2023!
      ME_CONFIG_MONGODB_SERVER: mongo-db
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
    depends_on:
      - mongo-db