version: "3"

services:
  frontend:
    image: docker-hub.montreal.aniere.fr/coiffex/frontend:latest
    ports:
      - 127.0.0.1:9080:80
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true

  backend:
    image: docker-hub.montreal.aniere.fr/coiffex/backend:latest
    ports:
      - 127.0.0.1:9081:8080
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true
      