version: "3"

services:
  frontend:
    image: docker-hub.montreal.aniere.fr/coiffex/frontend:latest
    ports:
      - 127.0.0.1:9080:80
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=true

  backend:
    image: docker-hub.montreal.aniere.fr/coiffex/backend:latest
    ports:
      - 127.0.0.1:9081:8080
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true

  database:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 127.0.0.1:5432:5432
    volumes: 
      - ./database-data:/var/lib/postgresql/data

  database-ui:
    image: dpage/pgadmin4
    restart: unless-stopped
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - ./database-ui-data:/var/lib/pgadmin
    links:
      - database